version: "3.9"

services: 
  mysql:
    image: mysql
    container_name: node26-images-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=node26-images
    ports:
      - 3306:3306

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node26-images-api
    env_file:
      - .env
    ports:
      - 4000:4000
    depends_on:
      - mysql
    command: 
      [
        "./wait-for", 
        "mysql:3306", 
        "--", 
        "node", 
        "./src/index.js"
      ]